### ISSUE TITLE
Documentation for Global Indexes

### ISSUE THREAD

**Issue by mgomes** [babbel/dynameister#28]
Would it be possible to add some info to the README for global indexes? Specifically I am having a hard time figuring out:

1. Setting capacity levels on the Global Index
2. Querying the Global Index

Thanks! This gem has a really great API overall.

**Comment by baschtl** [comment]
Hey @mgomes,

taking the example from the documentation you should be able to do this:

```ruby
class Cat
  field :pet_food
  field :feed_at, :datetime

  table hash_key: { name: :number }, range_key: { created_at: :string }

  local_index :feed_at

  global_index [ { pet_food: :number }, :feed_at], projection: :keys_only, throughput: [2, 3]
end
```

In this example I set the projection an the throughput for the global index of `Cat`.

You can query a specific index by its name using the `.index()` method within a query, e.g.:

```ruby
Book.scan(name: 'The Monkey').index('by_monkeys').all
```

@nicsnet Please, correct me if I am wrong.

**Comment by mgomes** [comment]
If you were to try and query the indexed keys then, would it be:

```ruby
Book.query(pet_food: 2, feed_at: 1.day.from_now).index('by_monkeys')
```

If so, where does the name of the index come from in this example?

Thanks.

**Comment by baschtl** [comment]
Small correction:

```ruby
Cat.query(pet_food: 2).and(feed_at: 1.day.from_now).index('by_pet_foods_and_feed_ats')
```
The index is auto-generated right now and cannot be overwritten (correct me if I am wrong @nicsnet and @pixelpogo), cf. https://github.com/babbel/dynameister/blob/v0.0.5/lib/dynameister/indexes/global_index.rb. This might be a feature request if you need to overwrite it. :)

If you want to know what indexes are defined on your model and what their name is you should be able to do this:

```ruby
# for global indexes
Cat.global_indexes # returns the GlobalIndex instances
Cat.global_indexes.map(&:name) # returns their names

# for local indexes
Cat.local_indexes # returns the LocalIndex instances
Cat.local_indexes.map(&:name) # returns their names
```

All the above was written based on the code as I do not have a running environment right now. I hope this helps. :)

**Comment by mgomes** [comment]
:raised_hands:  Awesome. Thanks so much!
